### ISSUE TITLE
wishlist, 아이디 중복확인 API data 수정 요청

### ISSUE THREAD

**Issue by ahnlook** [masters2023-2nd-project-05/second-hand#122]
### 관심목록 

https://www.notion.so/second-hand-team5/5727ac29389949b1a79de39ea0483183?pvs=4
위 API 명세에서 `categories` 값이 필요하여 추가 요청드립니다. ❤️

```javascript
{
	maxPage: number
	categories: [number, number ...]
	items: [
		{ 
		id: number,
		title: string,
		region: number,
		thumbnailUrl: string,
		createdAt: string,
		price: number,
		status: { onSale | reservation | soldOut },
		chatCount: number,
		likesCount: number
		}
	]
}
```

--------

### 아이디 중복확인을 할 수 있다 
![image](https://github.com/masters2023-2nd-project-05/second-hand/assets/107349637/781f9626-1206-4415-b93b-989898d1bc26)
저희 아이디 조건에 맞는 일반 회원 아이디가 없어용 ㅜㅜ 
- 6~12자 이내의 영소문자/숫자만 입력가능하세요
- 영소문자/숫자 혼합 6~12자로 입력하세요

=> `대문자` X, `-` X

**Comment by jaea-kim** [comment]
해당 부분 카테고리 조회 API로 분리했는데 확인해주세요~
