### ISSUE TITLE
[API] 상품 글 상세조회 createdAt 컬럼 추가 요쳥

### ISSUE THREAD

**Issue by ahnlook** [masters2023-2nd-project-05/second-hand#212]
https://www.notion.so/second-hand-team5/6600e14f26044bb183881b8d93ce8543?pvs=4

노션 명세에는 `createdAt` 컬럼이 있는데 swagger에는 누락된 것 같아요!
추가 부탁드리겠습니다!

➕ `isLike`로 받기로 한 키 값이 `like`로 들어오는데 어떤 걸로 통일해서 주실 건지 알려주시면 감사하겠습니다 🙏🏻💕

**Comment by jaea-kim** [comment]
isLike로 수정하겠습니당~

**Comment by jaea-kim** [comment]
isLike로 통일합니당~

**Comment by jaea-kim** [comment]
수정 완!
